<!-- BEGIN: FOOTER -->

	</div>
</div>
<footer>
	<div class="container">
		<div class="pull-right">
			Generated by <a href="http://cotonti.com" target="blank">CMF Cotonti</a><br/>
			Powered by <a href="http://cmsworks.ru" target="blank">CMSWorks.ru</a>
		</div>
		&copy; {PHP|cot_date('Y)} {PHP.cfg.maintitle}
	</div>
</footer>

{FOOTER_RC}
</body>
</html>
<!-- END: FOOTER -->