<!-- BEGIN: FOOTER -->

	</div>
</div>
<div id="footer" class="container">
	<div class="floatright">
		Generated by <a href="http://cotonti.com" target="blank">CMF Cotonti</a><br/>
		Powered by <a href="http://cmsworks.ru" target="blank">CMSWorks.ru</a>
	</div>
	&copy; 2013 {PHP.cfg.maintitle}
</div>

{FOOTER_RC}
</body>
</html>
<!-- END: FOOTER -->